version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}  # Loaded from .env or env var
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Maps host port 3000 to container port 80
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge